### ISSUE TITLE
Research how to make the terrain's look photorealistic in unity

### ISSUE THREAD

**Issue by RMSteenwijk** [Nexus-Aurora/na-unity-virtual-colony-experimental#10]

**Comment by mmaclaurin** [comment]
MicroSplat is not open source but it is free and extremely high quality for doing PBR rendering of terrains with either Standard, HDRP, or URP. Definitely worth considering.

Recovering all the PBR channels from Mars scans is a challenging question.

**Comment by RMSteenwijk** [comment]
@mmaclaurin Yeah we can't consider something not open source, when we are open-source 

We have some ideas on how to implement a semi realistic looking landscape and a guy pretty proficient at making materials, for his skills look at:
https://i.redd.it/h8desoufr1351.jpg

We are going to have to innovate here because a cut & copy paste terrain just isn't exciting enough for the public to feel immersed. 

Some of my ideas:
- Terrain Surface Displacement
- Tessellation
- Basic Terrain Parallax shader
- Basic random details generation based on height maps

**Comment by PranavKishan213** [comment]
Are we not allowed to use any closed source? It seems silly, as there is no reason we shouldn't, as long as we credit them and we are not giving away their proprietary tech, just the product from such which is licensed to us.

**Comment by PranavKishan213** [comment]
I found this, and it seems really great, depending on if our artists have very beefy computers.
https://quadspinner.com/Gaea/

**Comment by PranavKishan213** [comment]
And since I assume we are a non-profit, we can freely use these programs...

**Comment by nmeln** [comment]
@PranavKishan213 I think project leads don't want to mess with licenses and such, instead focusing on delivering MVP as soon as possible. 

But that's a tradeoff of course because then the team needs to create workarounds which takes time.

Anyway, I'm just a spectator at the moment, just wanted to share some thoughts. I'm sure maintainers can elaborate on these decisions.

**Comment by mmaclaurin** [comment]
If the goal is speed than reinventing freely available wheels seems not great. MicroSplat for example would take a long time to replicate. 

You could easily simply point users to microsplats free version to download themselves. No licensing needed. 

For me, I was interested in contributing but not if it’s going to be doing things the hard way and spending time reinventing established tech. I’ll keep watching to see how this shakes out.

**Comment by PranavKishan213** [comment]
That is why I was also confused. Several of the artists in the project freely use proprietaries, such as Maya or 3DS Max, so the sudden restriction came as a surprise to me.

**Comment by mmaclaurin** [comment]
Not to put too fine a point on it, but Unity itself is closed source and required to run the project.

**Comment by olawlor** [comment]
The URP branch uses HRSC + CTX terrain, with two layers of tiling detail textures (Assets/Terrain/Texture).  If somebody would like to go farther, like terrain-specific textures, our Mars Terrain Shader is designed to be extended like this idea:  https://tech.innogames.com/terrain-shader-in-unity/
