### ISSUE TITLE
Create a sky box or render settings look similar too the Mars atmosphere

### ISSUE THREAD

**Issue by RMSteenwijk** [Nexus-Aurora/na-unity-virtual-colony-experimental#11]

**Comment by DeadlyMagikarps** [comment]
> I did some initial research on how to accomplish this in Unity. We should use a [Physically Based Sky](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@8.1/manual/Override-Physically-Based-Sky.html).

I'd be careful unless we can basically do it at this level: http://overcloud.me/

I'm concerned of the cost of a dynamic sky that's default. Definitely check it out and see. It might work better than expected. 

PBR materials however is a different story like below:
https://blog.viromedia.com/asset-pipeline-exporting-pbr-textured-3d-models-for-ar-vr-arkit-arcore-c570423c68aa

**Comment by jgwinner** [comment]
I may be able to help. I have a skybox in Vue I made for my VR book, 

There are SO few clouds on Mars, I think a general pano would work - however, there are of course a lot of dust storms.

They don't look like most pictures of sandstorms on Earth - honestly, it's just a darker sky and a lot of general CGI 'fog' I think.

https://www.teslarati.com/nasa-curiosity-rover-selfie-mars-storm/   
and
https://earthsky.org/space/understanding-mars-dust-storms 

Those skies I can do easily. I was hoping to do a sunset animation, but that turns out to be difficult. I thought I knew Vue pretty well. Tempted to upgrade to Terragen. Does anyone have it? I could do the work and then upload the world file.

Do you want a skybox or a true pano?

**Comment by jgwinner** [comment]
Oh, the physically based sky is nice, but we need to make sure it does the blue sky near the sunset correctly.

**Comment by DeadlyMagikarps** [comment]
> I may be able to help. I have a skybox in Vue I made for my VR book,
> 
> There are SO few clouds on Mars, I think a general pano would work - however, there are of course a lot of dust storms.
> 
> They don't look like most pictures of sandstorms on Earth - honestly, it's just a darker sky and a lot of general CGI 'fog' I think.
> 
> https://www.teslarati.com/nasa-curiosity-rover-selfie-mars-storm/
> and
> https://earthsky.org/space/understanding-mars-dust-storms
> 
> Those skies I can do easily. I was hoping to do a sunset animation, but that turns out to be difficult. I thought I knew Vue pretty well. Tempted to upgrade to Terragen. Does anyone have it? I could do the work and then upload the world file.
> 
> Do you want a skybox or a true pano?

I am not sure if the license "Freeware/commercial" can be used for an open source project. This would be need to researched more before proceeding. 

When you are saying Pano, you are implying a spherical mapping in space for a HDRI or similar image right? That will definitely work and I'm hoping we have a good image that we can use to create the skybox. (Skybox is just a term now, so, technically, we can you pano, 360, 180, 6-sided cube, and other mappings to create this skybox in both square or spherical form).

I've never used Vue before so I am not sure if it is easily from Vue to Unity. I've seen people try exporting heightmaps from them then remake that map in another 3D program. 



> Oh, the physically based sky is nice, but we need to make sure it does the blue sky near the sunset correctly.

Ya, that requires tweaking with atmospheric for and other settings. Still waiting on some more examples or more specific data. Physically Based Sky's can look really nice. but I only know the basics and someone with better knowledge or experience building PBS should take lead in it at some point.

**Comment by jgwinner** [comment]
I would donate the image created by Vue to the project, so there are no issues.

And yes, I'd generate an HDRI if you wanted. I'm asking specifically what format you want! :) So you don't have to worry about Vue to Unity - I'll just give you a 360 Pano, that would be the easiest. Do we know the location you'd want? I could render the far away terrain also.

I got fairly good at taking DEM's and generating height maps. I've been working on mars rendering off and on for a while.

Without a sunset, I can get that done really quickly. I'm having a problem with the rendering algorithms doing sunsets properly. The dust on Mars will make the 'orange' of sunset look blue. The sun still looks white though, and the atmosphere still looks brown/beige. Not red.

**Comment by DeadlyMagikarps** [comment]
> And yes, I'd generate an HDRI if you wanted. I'm asking specifically what format you want! :) So you don't have to worry about Vue to Unity - I'll just give you a 360 Pano, that would be the easiest. Do we know the location you'd want? I could render the far away terrain also.

No Idea where. That will be a question for @RMSteenwijk. My impressions was a "generic" location. Format wise, a Jpg, tiff or png is the universally accepted in Unity from my experience. 

Feel free to play around with it on my branch if you fork it or clone it: https://github.com/DeadlyMagikarps/vr-unity-demo/tree/PhysicallyBasedSky

This is the working edition on my end (and the pr here if it gets approved to start out). All hands on deck.

**Comment by jgwinner** [comment]
Quick update: The "Sunset" code is a bit more complicated than I thought; Vue failed me, so I'm working with Terragen. However, the colors at 'sunset' seem to be wrong when the sun is higher in the sky. So I'm taking a look at that.

Again, given the lack of clouds, and on the ground, dust storms seem to be gradual 'fog' (other than dust devil twisters) I'm really thinking maybe a procedural sky would be better.

I did get some great MOLA data of the terrain around the new site so I can do physically accurate distant mountains.

        == John ==

**Comment by DeadlyMagikarps** [comment]
See #25 for HDRI skybox and basic volumetric fog using HDRP.

**Comment by olawlor** [comment]
The URP branch also has a shader-based Mars sky (Assets/Atmosphere/Mars Skybox Shader).  Closing this issue since we now have several solutions in place.

**Comment by jgwinner** [comment]
Sorry for letting you guys down - I actually purchased Terragen, but got lost trying to get the right haze around the sun; blue at night, neutral / reddish during the day per all the pictures (and the sun disk should be white at all times). Plus, I need to get some incoming cash, busy chasing leads.

Glad there's a solution.

        == John ==
